name: Multi-language Design Patterns Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install compilers
        run: |
          sudo apt update
          sudo apt install -y g++ mono-mcs default-jdk zip

      - name: Compile C++ files
        run: |
          mkdir -p bin/cpp
          for file in cpp/*.cpp; do
            g++ "$file" -o "bin/cpp/$(basename ${file%.cpp})"
          done

      - name: Compile C# files
        run: |
          mkdir -p bin/csharp
          for file in csharp/*.cs; do
            mcs "$file" -out:"bin/csharp/$(basename ${file%.cs}).exe"
          done

      - name: Compile Kotlin files
        run: |
          mkdir -p bin/kotlin
          for file in kotlin/*.kt; do
            kotlinc "$file" -include-runtime -d "bin/kotlin/$(basename ${file%.kt}).jar"
          done

      - name: Create ZIP archive
        if: github.event_name == 'release'
        run: |
          echo "[🔧] Creating ZIP..."
          ls -R bin/
          zip -r compiled_outputs.zip bin/
          echo "[✅] ZIP created:"
          ls -lh compiled_outputs.zip

      - name: Upload ZIP to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: compiled_outputs.zip